openapi: 3.0.0
info:
  version: 0.2.0
  title: CityRanks
servers:
  - url: 'https://e933812d-a479-4a65-9fac-233e0468311a.mock.pstmn.io'
paths:
  /cities:
    get:
      summary: 'Cities list: Return list of cities with image urls'
      operationId: listCities
      tags:
        - city
      responses:
        '200':
          description: 'Sample response: List of cities sorted by ID'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cities'
              examples:
                Cities:
                  $ref: '#/components/examples/Cities'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /cities/{id}:
    summary: 'Represents a city details'
    get:
      summary: 'City details from ID: Return city details from given id'
      operationId: getCityDetails
      parameters:
        - name: id
          in: path
          description: 'City ID'
          required: true
          schema:
            $ref: '#/components/schemas/CityId'
            example: 1
      tags:
        - city
      responses:
        '200':
          description: 'Sample response: City details from id'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/City'
              examples:
                1:
                  $ref: '#/components/examples/CityDetails'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /cities/{id}/visitors:
    summary: 'Represents a list of city visitors'
    get:
      summary: 'City visitors from ID: Return city visitors from given id'
      operationId: getCityVisitors
      parameters:
        - name: id
          in: path
          description: 'City ID'
          required: true
          schema:
            $ref: '#/components/schemas/CityId'
            example: 1
      tags:
        - city
        - visitor
      responses:
        '200':
          description: 'Sample response: City visitors from id'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Visitors'
              examples:
                1:
                  $ref: '#/components/examples/Visitors'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  examples:
    Cities:
      description: Example cities list
      value:
        - id: 1
          name: Wroclaw
          image: https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Herb_wroclaw.svg/404px-Herb_wroclaw.svg.png
        - id: 2
          name: Warsaw
          image: https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/POL_Warszawa_COA.svg/286px-POL_Warszawa_COA.svg.png
        - id: 3
          name: Cracow
          image: https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/POL_Krak%C3%B3w_COA.svg/1200px-POL_Krak%C3%B3w_COA.svg.png
    CityDetails:
      description: Example city details
      value:
        id: 1
        name: Wroclaw
        image: https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Herb_wroclaw.svg/404px-Herb_wroclaw.svg.png
        rating: 5.5
    Visitors:
      description: Example city visitors
      value:
        - id: 1
          name: Donald Trump
        - id: 2
          name: Vladymir Putin
        - id: 3
          name: Angela Merkel
  schemas:
    CityId:
      type: integer
      format: int64
    City:
      type: object
      required:
        - id
        - name
      properties:
        id:
          $ref: '#/components/schemas/CityId'
        name:
          type: string
        image:
          type: string
        rating:
          type: number
          format: double
    Cities:
      type: array
      items:
        $ref: '#/components/schemas/City'
    Visitor:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    Visitors:
      type: array
      items:
        $ref: '#/components/schemas/Visitor'
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string